name: Incremental Flashcard Generation

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2:00 AM UTC

# Permissions for the default GITHUB_TOKEN
permissions:
  contents: write

jobs:
  generate-flashcards:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymupdf tqdm azure-ai-inference azure-core gdown
      
      - name: Download previous progress
        uses: actions/download-artifact@v4
        with:
          name: flashcard-progress
          path: progress/
        continue-on-error: true
      
      - name: Download PDF from Google Drive
        run: |
          mkdir -p pdf_to_flashcards/test_pdfs
          # Using gdown for reliable Google Drive downloads
          gdown --id 1KSe2zJGJL69gWQ1nsm0sWxvnEIy2wY4F -O pdf_to_flashcards/test_pdfs/CS-TEXTBOOK.pdf
      
      - name: Debug repository structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing all files:"
          find . -type f | grep -v ".git" | sort
          # Verify PDF file was downloaded correctly
          ls -la pdf_to_flashcards/test_pdfs/CS-TEXTBOOK.pdf
      
      - name: Debug repository files
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          find . -type f -name "*.py" | sort
      
      - name: Extensive debug
        run: |
          echo "Working directory: $(pwd)"
          echo "Repository contents (detailed):"
          find . -type f | sort
          echo "Branch information:"
          git branch -a
          echo "Git status:"
          git status
      
      - name: Run incremental flashcard generation
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          python comprehensive_flashcard_generator.py pdf_to_flashcards/test_pdfs/CS-TEXTBOOK.pdf --max-requests 5
          mkdir -p progress
      
      - name: Save progress
        uses: actions/upload-artifact@v4
        with:
          name: flashcard-progress
          path: progress/
          retention-days: 90
      
      - name: Save generated flashcards
        uses: actions/upload-artifact@v4
        with:
          name: flashcards
          path: comprehensive_flashcards/
          retention-days: 90
      
      - name: Check completion status
        id: check-completion
        run: |
          if [ "$FLASHCARDS_COMPLETED" = "true" ]; then
            echo "completed=true" >> $GITHUB_OUTPUT
          else
            echo "completed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit results if completed
        if: steps.check-completion.outputs.completed == 'true'
        env:
          # Use PAT for git operations
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add comprehensive_flashcards/
          git commit -m "Add completed flashcards [skip ci]"
          # Use token for authentication
          git push https://${GH_TOKEN}@github.com/Abdelrahman-Fathy0/Automated-fashcard-maker.git
