name: Incremental Flashcard Generation

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  generate-flashcards:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download progress if exists
        uses: actions/download-artifact@v3
        with:
          name: flashcard-progress
          path: progress/
        continue-on-error: true
        
      - name: Run incremental flashcard generation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python comprehensive_flashcard_generator.py pdf_to_flashcards/test_pdfs/CS-TEXTBOOK.pdf --max-requests 100
          
      - name: Save progress
        uses: actions/upload-artifact@v3
        with:
          name: flashcard-progress
          path: progress/
          retention-days: 90
          
      - name: Save generated flashcards
        uses: actions/upload-artifact@v3
        with:
          name: flashcards
          path: comprehensive_flashcards/
          retention-days: 90
          
      - name: Check completion status
        id: check-completion
        run: |
          if [ "$FLASHCARDS_COMPLETED" = "true" ]; then
            echo "::set-output name=completed::true"
          else
            echo "::set-output name=completed::false"
          fi
          
      - name: Commit results if completed
        if: steps.check-completion.outputs.completed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add comprehensive_flashcards/
          git commit -m "Add completed flashcards [skip ci]"
          git push
