name: Generate Comprehensive Flashcards

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: 'Path to PDF file'
        required: true
        default: 'pdfs/textbook.pdf'
      model:
        description: 'AI model to use'
        required: true
        default: 'gpt4o-mini'
      max_requests_per_run:
        description: 'Maximum API requests per run'
        required: true
        default: '140'
  schedule:
    # Run daily at 1 AM UTC
    - cron: '0 1 * * *'

jobs:
  generate-flashcards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-inference PyMuPDF tqdm

      - name: Download previous progress
        uses: actions/download-artifact@v3
        with:
          name: flashcard-progress
          path: progress
        continue-on-error: true

      - name: Create progress directory if not exists
        run: mkdir -p progress

      - name: Set default environment variables
        run: |
          echo "PDF_PATH=${{ github.event.inputs.pdf_path || 'pdfs/textbook.pdf' }}" >> $GITHUB_ENV
          echo "MODEL=${{ github.event.inputs.model || 'gpt4o-mini' }}" >> $GITHUB_ENV
          echo "MAX_REQUESTS=${{ github.event.inputs.max_requests_per_run || '140' }}" >> $GITHUB_ENV

      - name: Run incremental flashcard generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python incremental_comprehensive_flashcard_generator.py "$PDF_PATH" --model "$MODEL" --max-requests "$MAX_REQUESTS"
          echo "FLASHCARDS_COMPLETED=${FLASHCARDS_COMPLETED}" >> $GITHUB_ENV

      - name: Upload progress as artifact
        uses: actions/upload-artifact@v3
        with:
          name: flashcard-progress
          path: progress/

      - name: Upload completed flashcards if generation is complete
        if: env.FLASHCARDS_COMPLETED == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: completed-flashcards
          path: comprehensive_flashcards/

      - name: Create notification issue when complete
        if: env.FLASHCARDS_COMPLETED == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🎉 Flashcard Generation Complete!',
              body: `Your comprehensive flashcards are ready!

### Details
- **PDF processed**: \`${process.env.PDF_PATH}\`
- **Model used**: \`${process.env.MODEL}\`
- **Date completed**: ${new Date().toISOString()}

### How to Access Your Flashcards
1. Go to the [Actions tab](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
2. Scroll down to "Artifacts"
3. Download the "completed-flashcards" file
4. Extract the ZIP file to access your flashcards in various formats

The flashcards have been generated with comprehensive coverage of all concepts and components, ensuring all related topics are covered.`
            });
            console.log('Created issue #' + result.data.number);
