name: Generate Comprehensive Flashcards

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: 'Path to PDF file'
        required: true
        default: 'pdfs/textbook.pdf'
      model:
        description: 'AI model to use'
        required: true
        default: 'gpt4o-mini'
      max_requests_per_run:
        description: 'Maximum API requests per run'
        required: true
        default: '140'
  schedule:
    # Run daily at 1 AM UTC
    - cron: '0 1 * * *'

jobs:
  generate-flashcards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-inference PyMuPDF tqdm

      - name: Download previous progress
        uses: actions/download-artifact@v3
        with:
          name: flashcard-progress
          path: progress
        continue-on-error: true

      - name: Create progress directory if not exists
        run: mkdir -p progress

      - name: Set default environment variables
        run: |
          echo "PDF_PATH=${{ github.event.inputs.pdf_path || 'pdfs/textbook.pdf' }}" >> $GITHUB_ENV
          echo "MODEL=${{ github.event.inputs.model || 'gpt4o-mini' }}" >> $GITHUB_ENV
          echo "MAX_REQUESTS=${{ github.event.inputs.max_requests_per_run || '140' }}" >> $GITHUB_ENV

      - name: Run incremental flashcard generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python incremental_comprehensive_flashcard_generator.py "$PDF_PATH" --model "$MODEL" --max-requests "$MAX_REQUESTS"
          echo "FLASHCARDS_COMPLETED=${FLASHCARDS_COMPLETED}" >> $GITHUB_ENV

      - name: Upload progress as artifact
        uses: actions/upload-artifact@v3
        with:
          name: flashcard-progress
          path: progress/

      - name: Upload completed flashcards if generation is complete
        if: env.FLASHCARDS_COMPLETED == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: completed-flashcards
          path: comprehensive_flashcards/

      - name: Send email notification if completed
        if: env.FLASHCARDS_COMPLETED == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Flashcard Generation Complete"
          body: |
            Your comprehensive flashcards have been successfully generated!
            
            Download them from the GitHub Actions artifacts at:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            This automated process used the ${{ env.MODEL }} model and processed your textbook with hierarchical concept analysis to ensure comprehensive coverage of all topics and components.
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
          attachments: comprehensive_flashcards/run_*/concept_coverage.json
