name: Generate Comprehensive Flashcards

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: 'Path to PDF file'
        required: true
        default: '/workspaces/codespaces-models/pdf_to_flashcards/test_pdfs/CS-TEXTBOOK.pdf'
      model:
        description: 'AI model to use'
        required: true
        default: 'gpt4o-mini'
      max_requests_per_run:
        description: 'Maximum API requests per run'
        required: true
        default: '140'
  schedule:
    # Run daily at 1 AM UTC
    - cron: '0 1 * * *'

jobs:
  generate-flashcards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-inference PyMuPDF tqdm

      - name: Download previous progress
        uses: actions/download-artifact@v4
        with:
          name: flashcard-progress
          path: progress
        continue-on-error: true

      - name: Create progress directory if not exists
        run: mkdir -p progress

      - name: Set default environment variables
        run: |
          echo "PDF_PATH=${{ github.event.inputs.pdf_path || '/workspaces/codespaces-models/pdf_to_flashcards/test_pdfs/CS-TEXTBOOK.pdf' }}" >> $GITHUB_ENV
          echo "MODEL=${{ github.event.inputs.model || 'gpt4o-mini' }}" >> $GITHUB_ENV
          echo "MAX_REQUESTS=${{ github.event.inputs.max_requests_per_run || '140' }}" >> $GITHUB_ENV

      - name: Run incremental flashcard generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python incremental_comprehensive_flashcard_generator.py "$PDF_PATH" --model "$MODEL" --max-requests "$MAX_REQUESTS"
          echo "FLASHCARDS_COMPLETED=${FLASHCARDS_COMPLETED}" >> $GITHUB_ENV

      - name: Upload progress as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flashcard-progress
          path: progress/

      - name: Upload completed flashcards if generation is complete
        if: env.FLASHCARDS_COMPLETED == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: completed-flashcards
          path: comprehensive_flashcards/

      # Use a simpler approach for notification
      - name: Create completion summary
        if: env.FLASHCARDS_COMPLETED == 'true'
        run: |
          echo "### 🎉 Flashcard Generation Complete! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Your comprehensive flashcards are ready to download from the artifacts section." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Details:**" >> $GITHUB_STEP_SUMMARY
          echo "- Model used: $MODEL" >> $GITHUB_STEP_SUMMARY
          echo "- PDF processed: $PDF_PATH" >> $GITHUB_STEP_SUMMARY
          echo "- Download the 'completed-flashcards' artifact to access your files" >> $GITHUB_STEP_SUMMARY

      # Use a simpler GitHub issue creation approach
      - name: Create notification issue
        if: env.FLASHCARDS_COMPLETED == 'true'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 🎉 Flashcard Generation Complete!
          content-filepath: ./issue-body.md
          token: ${{ secrets.GITHUB_TOKEN }}

      # Create the issue content file
      - name: Prepare issue content
        if: env.FLASHCARDS_COMPLETED == 'true'
        run: |
          cat > issue-body.md << EOL
          Your comprehensive flashcards are ready!

          ### Details
          - **PDF processed**: \`${PDF_PATH}\`
          - **Model used**: \`${MODEL}\`
          - **Date completed**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

          ### How to Access Your Flashcards
          1. Go to the Actions tab in this repository
          2. Click on the most recent workflow run
          3. Scroll down to "Artifacts"
          4. Download the "completed-flashcards" file
          5. Extract the ZIP file to access your flashcards in various formats

          The flashcards have been generated with comprehensive coverage of all concepts and components, ensuring all related topics are covered.
          EOL
